name: TryHackMe Badge

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
jobs:
  tryhackme-badge-update:
    name: Update TryHackMe Badge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: p4p1/tryhackme-badge-workflow@main
        with:
          username: "Kalinkaa"
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
